name: Run Robot Framework Tests with Allure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Xvfb
        run: |
         sudo apt-get update
         sudo apt-get install -y xvfb
         Xvfb :99 -ac -screen 0 1920x1080x24 &
         echo "DISPLAY=:99" >> $GITHUB_ENV  

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework==7.3.2
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests
          pip install robotframework-faker
          pip install allure-robotframework

      
      - name: Run Robot Framework tests
        continue-on-error: false
        run: |
          mkdir -p allure-results # Garante que a pasta exista antes de rodar os testes
          python -m robot --listener allure_robotframework:allure-results scripts/
          

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/

      - name: Publicar Allure Report online (GitHub Pages)
        uses: peaceiris/actions-gh-pages@v4
        if: always() # Roda mesmo se os testes falharem
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # A pasta 'allure-report' é onde a ação anterior gera o site estático
          publish_dir: allure-report
          # Define a branch de destino como 'gh-pages' ou 'main/docs'
          publish_branch: gh-pages
